@startuml Diagramme de séquence
title DSS pour le scénario Redémarrer
skinparam style strictuml
skinparam backgroundcolor transparent
skinparam defaultfontname Verdana

actor ":Joueur" as J
participant ":Système" as S

J -> S : redémarrerJeu()
@enduml
